# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Seazones' Blog

on:
  push:
    branches: 
            - master

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@master
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build
        run: npm install
             npm build post:dev

  publish-ghr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -name: publish 
       env:
           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
